Add ShellCheck for build script to CI
Signed-off-by: Florian Hotze <dev@florianhotze.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,6 +14,21 @@ env:
   OPENHAB_SNAPSHOT_VERSION: 5.1.0
 
 jobs:
+  shellcheck:
+    name: ShellCheck
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Setup environment
+        run: sudo -E bash -c set
+
+      - name: "ShellCheck Template/build"
+        shell: bash
+        run: |
+          if shellcheck -x -s bash Template/build; then echo "OK"; else echo "FAILED"; exit 1; fi
+
   generate-formulae:
     name: Generate Formulae from Template
     runs-on: ubuntu-latest
